export enum ModelMaterials {
  Red = 'Red',
  Blue = 'Blue',
  Green = 'Green',
  Yellow = 'Yellow',
  Orange = 'Orange',
  Purple = 'Purple',
  Pink = 'Pink',
  Brown = 'Brown',
  Black = 'Black',
  White = 'White',
  Gray = 'Gray',
  Cyan = 'Cyan',
  Magenta = 'Magenta',
  Lime = 'Lime',
  Olive = 'Olive',
  Maroon = 'Maroon',
  Navy = 'Navy',
  Teal = 'Teal',
  Violet = 'Violet',
  Indigo = 'Indigo',
}
